### ISSUE TITLE
Find project name

### ISSUE THREAD

**Issue by paulwellnerbou** [paulwellnerbou/sqlite-go-json#5]
It should not contain sqlite, as this project will be able to server content from other databases as well. Same for JSON: XML, BSON, GOB, JSONB, ... is possible as well.

**Comment by tbhanson** [comment]
Ok, I'll bite. :)

Here's a handful of ideas:
- DataLight
- LightweightDataSource
- GoForData
- MaybeDB (or even MaybeDeeBee) - not very descriptive, but has a nice ring
- SufficientData (a bit unwieldy, but plays on the old saying "insufficient data" and might raise a smile or two)

Cheers,

tbh

**Comment by paulwellnerbou** [comment]
"bee" sounds good... "databee"?

**Comment by tbhanson** [comment]
Yes, not bad. Rhythm like database, wannabe, and "bee" also conjurs a worker that goes forth and brings useful stuff back: works for me!

**Comment by paulwellnerbou** [comment]
Thanks for the input!

**Comment by tbhanson** [comment]
Sure, sorry I didn't reply til now. Not up on all my notification channels, alas. :)
